//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomUsageApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string No { get; set; }
        public Nullable<int> FacultyId { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
