//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomUsageApp.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_CHINEntities : DbContext
    {
        public DB_CHINEntities()
            : base("name=DB_CHINEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Building> Building { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<ScheduleTime> ScheduleTime { get; set; }
        public virtual DbSet<RegistrationTemp> RegistrationTemp { get; set; }
    
        public virtual int DELETE_REGTEMP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_REGTEMP");
        }
    
        public virtual int IMPORT_DATA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IMPORT_DATA");
        }
    }
}
