//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomUsageApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationTemp
    {
        public long ID { get; set; }
        public Nullable<double> YEAR { get; set; }
        public Nullable<double> SEMESTER { get; set; }
        public Nullable<double> FACCODE { get; set; }
        public string FACNAME { get; set; }
        public string FACABBR { get; set; }
        public Nullable<double> COURSECODE { get; set; }
        public string NAMEENGABBR { get; set; }
        public string TEACHTYPE { get; set; }
        public Nullable<double> SECTION { get; set; }
        public string DAY1 { get; set; }
        public string DAY2 { get; set; }
        public string DAY3 { get; set; }
        public string DAY4 { get; set; }
        public string DAY5 { get; set; }
        public string DAY6 { get; set; }
        public string DAY7 { get; set; }
        public string STARTTIME { get; set; }
        public string ENDTIME { get; set; }
        public Nullable<double> REALREG { get; set; }
        public Nullable<double> TOTALREG { get; set; }
        public string BUILDINGNAME { get; set; }
        public Nullable<double> BUILDINGNO { get; set; }
        public Nullable<double> ROOMNO { get; set; }
        public string ROOMTYPE { get; set; }
        public Nullable<double> NUMCLASSSEAT { get; set; }
        public string STUDYPROGRAM { get; set; }
    }
}
