//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomUsageApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleTime
    {
        public long Id { get; set; }
        public string Day { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<long> ScheduleId { get; set; }
        public Nullable<long> RoomId { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
